[package]
edition = "2021"
name = "core"
version = "0.1.0"

[[bin]]
name = "logos-core"
path = "src/main.rs"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.0"
serde = {version = "1.0.152", features = ["derive"]}
utils = {path = "../utils"}
