[workspace]
members = ["./services/*"]

[workspace.package]
description = "A news feed, a really good one!"
documentation = "https://github.com/rafaelrcamargo/logos"
authors = ["Rafael R. Camargo (https://github.com/rafaelrcamargo)"]
