name: "logos"

networks:
  localhost:
    driver: bridge

services:
  web:
    profiles:
      - donotstart
    build:
      context: ../clients/web
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../clients/web:/app
      - /app/node_modules
      - /app/.next

  redis: # Used for the OAuth2 server
    image: redis:alpine
    container_name: auth
    restart: always
    ports:
      - 6379:6379

  neo4j: # Used in the user service
    image: neo4j:4.4.2 # for now the rust driver is not compatible with neo4j 5.x
    container_name: user
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}

  nginx:
    image: nginx:alpine
    container_name: gateway
    restart: always
    ports:
      - 80:80
    volumes:
      - ../guard/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - localhost
