[package]
edition = "2021"
name = "gatekeeper"
version = "0.1.0"

[dependencies]
actix-cors.workspace = true
actix-session.workspace = true
actix-web.workspace = true
confy = "0.5.1"
dotenv_codegen.workspace = true
serde.workspace = true
utils.workspace = true
